#!/bin/bash
  		
				
printHelp() {
       echo "Usage: namechange -f find -r replace: string to modify"
       echo " -f The text to find in the filename"
       echo " -r The replacement text for the new filename"	
}

 while getopts ":hf:r:" opt; do


	case $opt in

	h)   echo "Printing Help Guide"  
		printHelp
		exit
		;;

	f)   find=$OPTARG
		;;

	r)   replace=$OPTARG
		;;
	\?) 
	     echo "Invalid option"
	     echo "Here is a help guide:"
	     printHelp
	     ;;
       esac
     done

     shift $((OPTIND-1))
     filename=$1
if [[ -e $filename ]];then
   	echo "$@ exists"
	newname=$(sed -e "s/$find/$replace/g" <<< $@)
	mv "./$@" "./$newname"
	echo "file has been changed"
else
	echo "User must provide valid file name"
	printHelp
	exit
fi
 

